=== Draycen/api_auto_test/test_case/xml/test_case.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.batar.cn"
	xmlns="http://www.batar.cn"
	elementFormDefault="qualified">
	<xs:element name="test_case" >
		<xs:complexType >
			<xs:all>
				<xs:element  name="case_api">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="case_name" type="xs:string"/>
							<xs:element name="case_user" type="xs:string"/>
							<xs:element name="case_category" type="xs:string"/>
							<xs:element name="case_module" type="xs:string"/>
							<xs:element name="case_function" type="xs:string"/>
							<xs:element name="case_active" type="xs:boolean" default="true"/>
							<xs:element name="case_debug" type="xs:boolean" default="true"/>
							<xs:element name="case_address" type="xs:string"/>
							<xs:element name="case_data_location" >
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="本地"/>
										<xs:enumeration value="文件"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="case_method" >
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="post"/>
										<xs:enumeration value="get"/>
										<xs:enumeration value="put"/>
										<xs:enumeration value="delete"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="case_data_type" >
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Form"/>
										<xs:enumeration value="Data"/>
										<xs:enumeration value="File"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="case_check_point">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="包含"/>
										<xs:enumeration value="不包含"/>
										<xs:enumeration value="等于"/>
										<xs:enumeration value="不等于"/>
										<xs:enumeration value="正则匹配"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="case_check_content" >
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:whiteSpace value="replace"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="case_request_data">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:whiteSpace value="replace"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="case_comment" type="xs:string"  />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Draycen/api_auto_test/test_case/xml/saler.xml
<?xml version="1.0" encoding="UTF-8" ?>
<test_case xmlns="http://www.batar.cn"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.batar.cn test_case.xsd">
    <case_api>
        <case_name>saler_1_001</case_name>
        <case_category>销售服务</case_category><case_user>system_saler</case_user>
        <case_module>查看销售信息</case_module>
        <case_function>查询存在的id对应的销售人员信息</case_function>
        <case_active>true</case_active>
        <case_debug>false</case_debug>
        <case_address>/saler/saler/1</case_address>
        <case_data_location>本地</case_data_location>
        <case_method>get</case_method>
        <case_data_type>Form</case_data_type>
        <case_check_point>包含</case_check_point>
        <case_check_content>"msg":"操作成功"</case_check_content>
        <case_request_data>{"id":1}</case_request_data>
        <case_comment>查询存在的id对应的销售人员信息</case_comment>
    </case_api>

</test_case>
